title: Drake Makes
description: Cayman is a clean, responsive theme for GitHub Pages.
url: "https://drakemakes.com"
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag