title: DrakeMakes
url: "https://drakemakes.com"
baseurl: ""
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /writing/:title.html

excerpt_separator: "<!--more-->"
